package com.stripcode.mybatis.generator.dao;

import com.stripcode.mybatis.generator.model.Wss;
import java.util.List;

public interface WssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wss
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wss
     *
     * @mbggenerated
     */
    int insert(Wss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wss
     *
     * @mbggenerated
     */
    List<Wss> selectAll();
}